# Generated by Django 4.1.6 on 2023-02-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicity', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='confirmacion_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
